export const DEFAULT_RECIPES = [
    {
      id: "cat_recipe1_80_10_10",
      name: "Chicken & Rabbit Mix",
      ingredients: [
        {
          id: "16",
          name: "Chicken Heart",
          totalWeight: 92,
          meatWeight: 92,
          boneWeight: 0,
          organWeight: 0,
          meat: 100,
          bone: 0,
          organ: 0,
          type: "Meat",
          unit: "g",
        },
        {
          id: "171",
          name: "Rabbit Neck skinless",
          totalWeight: 16,
          meatWeight: 4,
          boneWeight: 12,
          organWeight: 0,
          meat: 25,
          bone: 75,
          organ: 0,
          type: "Meat",
          unit: "g",
        },
        {
          id: "19",
          name: "Chicken Liver",
          totalWeight: 6,
          meatWeight: 0,
          boneWeight: 0,
          organWeight: 6,
          meat: 0,
          bone: 0,
          organ: 100,
          type: "Meat",
          unit: "g",
        },
        {
          id: "17",
          name: "Chicken Kidney",
          totalWeight: 6,
          meatWeight: 0,
          boneWeight: 0,
          organWeight: 6,
          meat: 0,
          bone: 0,
          organ: 100,
          type: "Meat",
          unit: "g",
        },
      ],
      ratio: "80:10:10",
    },
    {
      id: "cat_recipe2_75_15_10",
      name: "Beef & Duck Blend",
      ingredients: [
        {
          id: "48",
          name: "Beef Mince, boneless",
          totalWeight: 98,
          meatWeight: 98,
          boneWeight: 0,
          organWeight: 0,
          meat: 100,
          bone: 0,
          organ: 0,
          type: "Meat",
          unit: "g",
        },
        {
          id: "33",
          name: "Duck Neck",
          totalWeight: 28,
          meatWeight: 7,
          boneWeight: 21,
          organWeight: 0,
          meat: 25,
          bone: 75,
          organ: 0,
          type: "Meat",
          unit: "g",
        },
        {
          id: "32",
          name: "Duck Liver",
          totalWeight: 7,
          meatWeight: 0,
          boneWeight: 0,
          organWeight: 7,
          meat: 0,
          bone: 0,
          organ: 100,
          type: "Meat",
          unit: "g",
        },
        {
          id: "64",
          name: "Duck Kidney",
          totalWeight: 7,
          meatWeight: 0,
          boneWeight: 0,
          organWeight: 7,
          meat: 0,
          bone: 0,
          organ: 100,
          type: "Meat",
          unit: "g",
        },
      ],
      ratio: "75:15:10",
    },
    {
      id: "cat_recipe3_65_20_15",
      name: "Lamb & Turkey Feast",
      ingredients: [
        {
          id: "41",
          name: "Lamb Heart",
          totalWeight: 56,
          meatWeight: 56,
          boneWeight: 0,
          organWeight: 0,
          meat: 100,
          bone: 0,
          organ: 0,
          type: "Meat",
          unit: "g",
        },
        {
          id: "73",
          name: "Turkey Neck",
          totalWeight: 80,
          meatWeight: 48,
          boneWeight: 32,
          organWeight: 0,
          meat: 60,
          bone: 40,
          organ: 0,
          type: "Meat",
          unit: "g",
        },
        {
          id: "72",
          name: "Turkey Liver",
          totalWeight: 12,
          meatWeight: 0,
          boneWeight: 0,
          organWeight: 12,
          meat: 0,
          bone: 0,
          organ: 100,
          type: "Meat",
          unit: "g",
        },
        {
          id: "70",
          name: "Turkey Kidney",
          totalWeight: 12,
          meatWeight: 0,
          boneWeight: 0,
          organWeight: 12,
          meat: 0,
          bone: 0,
          organ: 100,
          type: "Meat",
          unit: "g",
        },
      ],
      ratio: "65:20:15",
    },
  ]
  